//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tickets()
        {
            this.ticketUser = new HashSet<ticketUser>();
        }
    
        public int id { get; set; }
        public Nullable<int> idSchedule { get; set; }
        public Nullable<int> row { get; set; }
        public Nullable<int> place { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<int> idDiscount { get; set; }
    
        public virtual discount discount { get; set; }
        public virtual schedule schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ticketUser> ticketUser { get; set; }
    }
}
